Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.hostname = "mysql"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.10.3"
  config.vm.network "forwarded_port", guest: 3306, host: 3307

  config.vm.provider "virtualbox" do |vb|
          vb.gui = false
          vb.memory = "1024"
          vb.name = "mysql"
  end
  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_ed25519.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end
end