apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "example-chart.labels" . | nindent 4 }}
    tier: backend
  name: {{ include "example-chart.backend.service.name" . }}
spec:
  ports:
  - port: {{ .Values.backend.service.port }}
    protocol: TCP
    targetPort: 8082
  selector:
    {{- include "example-chart.selectorLabels" . | nindent 4 }}
    tier: backend
