apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "example-chart.backend.defaultName" . }}
  labels:
    {{- include "example-chart.labels" . | nindent 4 }}
data:
  SVC_HOST: ""
  SVC_PORT: "{{ .Values.backend.service.port }}"
