apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "example-chart.labels" . | nindent 4 }}
    tier: gateway
  name: {{ include "example-chart.gateway.service.name" . }}
spec:
  ports:
    - nodePort: {{ .Values.gateway.service.nodePort }}
      port: {{ .Values.gateway.service.port }}
      protocol: TCP
      targetPort: {{ .Values.gateway.service.targetPort }}
  selector:
    {{- include "example-chart.selectorLabels" . | nindent 4 }}
    tier: gateway
  type: {{ .Values.gateway.service.type }}
