apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "example-chart.gateway.defaultName" . }}
  labels:
    {{- include "example-chart.labels" . | nindent 4 }}
data:
  SVC_HOST: {{ include "example-chart.backend.service.name" . }}
  SVC_PORT: "{{ .Values.backend.service.port }}"
  API_PORT: "{{ .Values.gateway.service.targetPort }}"
