backend:
  deployment:
    name:
    replicas: 2
  container:
    resources:
      limits:
        memory: 512Mi
        cpu: 400m
      requests:
        memory: 256Mi
        cpu: 200m
  service:
    name:
    port: 8082
  image:
    name: sliaptsou/backend
    tag: 0.1
    pullPolicy: IfNotPresent
  hpa:
    enabled: true
    name:
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 50

gateway:
  deployment:
    name:
    replicas: 2
  container:
    resources:
      limits:
        memory: 512Mi
        cpu: 200m
      requests:
        memory: 256Mi
        cpu: 100m
  service:
    name:
    #   Can be one of ClusterIP, NodePort or LoadBalancer
    type: NodePort
    port: 80
    nodePort: 30500
    targetPort: 8081
  image:
    name: sliaptsou/gateway
    tag: 0.1
    pullPolicy: IfNotPresent
  hpa:
    enabled: true
    name:
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 50
